stages:
  - build
  - test
  - build_docker
  - push_docker
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  
install_env:
  type: build
  script:
    - sudo apt-get update -qy
    - sudo apt-get install -y python-dev python-pip
    - sudo pip install django==1.10.5 gunicorn celery

test_app:
  type: test
  variables:
    RABBIT_USER: "guest"
    RABBIT_PASSWD: "guest"
    RABBIT_PORT_5672_TCP_ADDR: "127.0.0.1"
    RABBIT_PORT_5672_TCP_PORT: 5672
  script:
    - cd app/ && python manage.py test
    - cd app/ && python manage.py runserver

build_docker_app:
  type: build_docker
  script:
    - docker build -t registry.gitlab.com/mqll/mystream:app -f Dockerfile-app .

build_docker_encode:
  type: build_docker
  script:
    - docker build -t registry.gitlab.com/mqll/mystream:encode -f Dockerfile-encode .

push_docker_app:
  type: push_docker
  script:
    - docker push registry.gitlab.com/mqll/mystream:app

push_docker_encode:
  type: push_docker
  script:
    - docker push registry.gitlab.com/mqll/mystream:encode
