FROM mqll/django:1.10.5

RUN echo "deb http://ftp.fr.debian.org/debian jessie-backports main" >> /etc/apt/sources.list.d/backports.list

RUN apt-get update

RUN apt-get install -y ffmpeg \
        && rm -rf /var/lib/apt/lists/*

RUN pip install celery

WORKDIR /opt/

ADD app/ /opt/

ENV RABBIT_USER guest
ENV RABBIT_PASSWD guest

VOLUME ["/opt/media", "/var/log/celery", "/opt/db.sqlite3"]

ENTRYPOINT celery worker -A mystream \
            --loglevel=INFO
